#NUMPY

In [1]:
!pip install numpy



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np

## create array using numpy
# create 1D array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1, 2, 3,4,5])
arr2.reshape(1,5)
#1, one row and 5 columns


array([[1, 2, 3, 4, 5]])

In [10]:
arr2 = np.array([1, 2, 3,4,5])
arr2.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [11]:
arr2 = np.array([[1, 2, 3,4,5]])
arr2.shape


(1, 5)

In [ ]:
# 2D array
arr2 = np.array([[1,2,3], [2,3,4]])
print(arr2)
print(arr2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


In [16]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
#IDENTITY MATRIX
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#ATTRIBUTE OF NUMPY

arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr) 
print("Shape:", arr.shape) #output: (2, 3)
print("Dimension:", arr.ndim) #output: 2  
print("Size:", arr.size) # output :6
print("Data type:", arr.dtype) #output: int64
print("Item size:", arr.itemsize) #output: 8
print("Number of bytes:", arr.nbytes) #output: 48

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimension: 2
Size: 6
Data type: int64
Item size: 8
Number of bytes: 48


In [23]:
## Numpy Vectroized Operation

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#element wise addition
print("addition : ", arr1 + arr2)

#element wise subtraction
print("subtraction : ", arr1 - arr2)

#element wise multiplication    
print("multiplication : ", arr1 * arr2)

#element wise division
print("division : ", arr1 / arr2)

addition :  [11 22 33 44 55]
subtraction :  [ -9 -18 -27 -36 -45]
multiplication :  [ 10  40  90 160 250]
division :  [0.1 0.1 0.1 0.1 0.1]


In [24]:
## Universal Function

arr = np.array([1,2,3,4,5])
#square root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

#power  
print(np.power(arr, 2))

#sine
print(np.sin(arr))

#log
print(np.log(arr))

[1.         1.41421356 1.73205081 2.         2.23606798]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
[ 1  4  9 16 25]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]


In [27]:
## array slicing and indexing

arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print("Array : \n", arr)

Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [28]:
#how to accest any specific element
#arr(1,1)

arr[0]

array([1, 2, 3, 4])

In [32]:
arr[0][0]

np.int64(1)

In [33]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [34]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [35]:
arr[0:,2:]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

TO GET [3,4]
       [7,8]

In [38]:
print(arr[0] [0])
print(arr[0:2,2:])

1
[[3 4]
 [7 8]]


In [39]:
#6,7,10,11

print(arr[1: , 1:3])

[[ 6  7]
 [10 11]]


In [41]:
arr[1:] = 100
print(arr)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [ ]:
## STATISTICAL CONCEPT
# TO HAVE A MEAN OF 0 AND STANDARD DEVIATION OF 1   

In [44]:
data = np.array([1,2,3,4,5])
mean = np.mean(data)
std = np.std(data)
print(mean , std)

3.0 1.4142135623730951


In [45]:
normalized_data = (data - mean) / std
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
#variance
variance = np.var(data)
print(variance)

2.0


In [47]:
#median
median = np.median(data)
print(median)

3.0


In [48]:
data = np.array([1,2,3,4,5,6,7,8,9])
data>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [49]:
data[data>5]

array([6, 7, 8, 9])

In [50]:
data[(data>= 5) & (data<=8)]

array([5, 6, 7, 8])